### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by pcruiher08** [Loptt/hacking-taoe#1]
https://github.com/Loptt/hacking-taoe/blob/ed19cbc3922480defbfa6b5525b4f206ee619dc6/c-programming/char_array2.c#L15

Hi, I have an issue with this line, my compiler throws an error (I copied the log message at the bottom of this issue), can you help me? I really need to fix this.

log: "you are not a pro as Loptt".

**Comment by Loptt** [comment]
Hey pcruiher, sorry, this code is not meant for NPs like you. I am sorry for any inconvenience this may have caused
